Throw error if @Group key is missing
vapor/fluent-kit pull request #372
Opened 2020-08-05 21:21 UTC by tanner0101

Fixes an issue causing `@Group` to silently ignore missing data when decoding ().

`@Group` will now throw an error if required data is missing while decoding. This prevents force unwrap issues due to accessing uninitialized values.

2020-10-30 05:57 UTC, gwynne requested changes

2020-10-30 05:57 UTC, gwynne commented on Sources/FluentKit/Model/Fields+Codable.swift
> +            print(label, property)
Stray (debug?) `print`

2020-10-30 05:57 UTC, gwynne commented on Sources/FluentKit/Model/Fields+Codable.swift
> +                    codingPath: [self.key] + context.codingPath,
```suggestion
                    codingPath: context.codingPath + [self.key],
```

2020-10-30 05:57 UTC, gwynne commented on Sources/FluentKit/Model/Fields+Codable.swift
> +                    underlyingError: nil
```suggestion
                    underlyingError: context.underlyingError
```

2020-10-30 05:57 UTC, gwynne commented on Sources/FluentKit/Properties/Parent.swift
> +        self.decoder = decoder
```suggestion
        try self.$id.decode(from: container.superDecoder(forKey: .string("id")))
```
If this doesn't work, the implementation of the underlying `KeyedDecodingContainer` is wrong. Ref: https://github.com/apple/swift-corelibs-foundation/blob/main/Sources/Foundation/JSONEncoder.swift#L1604-L1618

2021-11-20 20:42 UTC, gwynne commented
This is technically semver-patch, but the change in behavior of thrown decoding errors could easily break existing error recovery logic, especially given how long this has been broken. Also people may be relying on the "ignores missing keys" behavior by now. Is it worth it to merge this?

2021-11-20 22:19 UTC, 0xTim commented
I think it's worth adding. If anyone retrieves the group and then tries to access the property it's gonna fail right?

2021-11-20 23:49 UTC, gwynne commented
I'm actually not sure if you would hit the `fatalError()` that way as things stand... if so then it's not a breaking change.

2021-11-21 09:24 UTC, Joannis commented
@gwynne from my experience with fluent-mongo, I believe I ran into `fatalError()` here.

2021-11-21 09:24 UTC, Joannis commented
Can be easily tested there

2021-11-23 11:50 UTC, 0xTim approved these changes

2021-11-23 11:50 UTC, 0xTim commented on Sources/FluentBenchmark/Tests/CodableTests.swift
> +            //XCTAssertEqual(ObjectIdentifier(type), ObjectIdentifier([String: Any].self), "\(type) != \([String: Any].self)")
We probably need to rewrite the test or find another way. At the very least the commented out code should go

2024-09-21 22:42 UTC, gwynne commented
Closing this due to age and lack of current applicability.

2024-09-21 22:42 UTC, closed without merging