Complex join conditions and composite-key parent relations
vapor/fluent-kit pull request #547
Opened 2023-02-03 09:21 UTC by gwynne

This release includes significant feature additions, cleanups, and improvements:

- More complex conditions are now supported when using `.join()` in queries; the `!=` operator is now supported, and conditions may be combined using `&&`.
- The new `@CompositeParent` property type may be used to reference a model which uses `@CompositeID` as the parent of another model.
- `ModelAlias` now works in  most cases that were previously broken; among other cases, it is now possible to alias models which specify a `space`.
- The poorly-considered "duplicate" `SQLList` type previously available in `FluentSQL` is now deprecated; use `SQLKit`'s version instead.
- Various code cleanups and minor performance improvements.
- `Fields` and `ModelAlias` now have detailed code documentation.
- A new type, `SomeCodingKey`, is now available, providing a complete implementation of `CodingKey` for convenience in various cases when arbitrary string or integer keys are desired.
- The SQL generated by FluentKit queries should now be slightly more consistent.

2023-02-03 16:44 UTC, gwynne commented on Sources/FluentBenchmark/Tests/FilterTests.swift
> +                .join(Foo.self, on: \FooOwner.$id == \Foo.$owner.$id)
With SQL databases it has no effect whatsoever. With Mongo it changes incorrect behavior to correct behavior.

2023-02-03 16:47 UTC, 0xTim requested changes

2023-02-03 16:47 UTC, 0xTim commented on Sources/FluentKit/Properties/CompositeParent.swift
> +public final class CompositeParentProperty<From, To>
Hate to be that person but would be good to have some API docs for new public stuff

2023-02-07 09:26 UTC, 0xTim approved these changes
🙌

2023-02-07 09:47 UTC, 0xTim approved these changes

2023-02-07 11:22 UTC, merged